apiVersion: apps/v1
kind: Deployment
metadata:
  name:
    flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
    template:
      metada:
        labels:
          app: flask-app
      spec:
        containers:
        - name: flask-app
          images: hirosetakahito/test-server 
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
