apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-nginx
spec:
  selector:
    matchLabels:
      app: flask-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: server-conf
          mountPath: /etc/nginx/conf.d/server.conf
          subPath: server.conf
      volumes:
      - name: server-conf
        configMap:
          name: server-conf
          items:
            - key: server.conf
              path: server.conf
---
apiVersion: v1
kind: Service
metadata:
  name: flask-nginx-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-nginx
